In [1]:
import numpy as np 
import pandas as pd

In [2]:
#suppress the use of scientific notation, set the maximum character width per line, limit the number of digits 2 decimal places
np.set_printoptions(suppress = True, linewidth=100, precision=2)

In [3]:
#DF with messy data of clinic appointments 
raw_clinic_data = pd.read_csv('clinic-appointments.csv')
raw_clinic_data

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,1
1,1074,Megan Strickland,69,F,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Y
2,1067,Amanda Schroeder,79,M,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Y
3,1072,Anthony Mcpherson,47,F,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1
...,...,...,...,...,...,...,...,...,...,...
995,1082,Thomas Roman,64,Female,"September 14, 25",2024/07/15,Robert Bass,General,Rs200.43,Yes
996,1008,Jack Cooper,67,F,"April 09, 25","June 20, 24",Christopher Smith,General,Rs244.49,No
997,1022,Christopher Brown,28,1,"February 13, 26",2024/06/13,Kimberly Johnson,Neurology,£154.48,N
998,1088,Michael Sullivan,65,F,2025/07/04,2024/04/15,Anthony Mccoy,Neurology,$434.95,0
999,1003,Perry Crawford,79,Male,05-Nov-2025,2024/07/22,Marvin Hicks,Cardiology,€102.23,Y

In [4]:
#making copy of original df
df = raw_clinic_data.copy()

In [5]:
#info about df: rows, NaN and non-null cells, datatypes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          1000 non-null   int64
 1   patient_name        1000 non-null   str
 2   age                 1000 non-null   int64
 3   gender              950 non-null    str
 4   appointment_date    1000 non-null   str
 5   booking_date        1000 non-null   str
 6   doctor              1000 non-null   str
 7   department          1000 non-null   str
 8   billing_amount      950 non-null    str
 9   follow_up_required  1000 non-null   str
dtypes: int64(2), str(8)
memory usage: 146.4 KB

In [6]:
#checing for duplicates
df.duplicated().sum()

np.int64(0)

In [7]:
#checing for duplicates in "patient_name" column
d = {x : y.iloc[:, :6]  for x, y in df.groupby(['patient_name']) if len(y) > 1}
d

{('Brian Davis',):      patient_id patient_name  age  gender appointment_date   booking_date
 240        1089  Brian Davis   72  female      26-Dec-2025  August 05, 24
 828        1050  Brian Davis   41  female      07-Feb-2026     2025/05/27,
 ('Christopher Brown',):      patient_id       patient_name  age gender appointment_date booking_date
 526        1072  Christopher Brown   49      F      26-Mar-2025   01/02/2025
 997        1022  Christopher Brown   28      1  February 13, 26   2024/06/13,
 ('Christopher Lopez',):      patient_id       patient_name  age gender appointment_date booking_date
 812        1053  Christopher Lopez   39      1       2026/01/15   2025/11/11
 873        1081  Christopher Lopez   45      M     March 21, 26  04-May-2024,
 ('Daniel White',):      patient_id  patient_name  age  gender appointment_date    booking_date
 674        1044  Daniel White   67    male       04/12/2025      07/13/2024
 915        1066  Daniel White   37  Female       May 25, 25  October 12, 24,
 ('Erika Davis',):      patient_id patient_name  age gender appointment_date  booking_date
 212        1057  Erika Davis   28      1      08-Jun-2025    2025/06/06
 769        1099  Erika Davis   42   Male      July 30, 25  March 09, 25,
 ('Jennifer Schwartz',):      patient_id       patient_name  age  gender appointment_date booking_date
 345        1014  Jennifer Schwartz   90     NaN  February 12, 26   08/14/2024
 459        1053  Jennifer Schwartz   30  Female  December 31, 25   2025/11/14,
 ('Katelyn Miller',):      patient_id    patient_name  age  gender appointment_date     booking_date
 73         1022  Katelyn Miller   23  Female      19-Feb-2026      16-Sep-2024
 396        1070  Katelyn Miller   78       M       12/19/2025  November 25, 24,
 ('Kyle Jones',):      patient_id patient_name  age gender appointment_date booking_date
 351        1082   Kyle Jones   29      M       2025/11/01  17-Mar-2025
 745        1051   Kyle Jones   52   Male   October 31, 25  01-Sep-2024,
 ('Michael Sullivan',):      patient_id      patient_name  age gender appointment_date booking_date
 434        1027  Michael Sullivan   63      M       07/09/2025  31-Jul-2024
 998        1088  Michael Sullivan   65      F       2025/07/04   2024/04/15,
 ('Pamela Davis',):      patient_id  patient_name  age  gender appointment_date      booking_date
 615        1077  Pamela Davis   78       0  December 19, 25  September 15, 25
 772        1005  Pamela Davis   27  Female       11/23/2025      April 12, 24,
 ('Regina Wilson',):      patient_id   patient_name  age gender appointment_date booking_date
 50         1040  Regina Wilson   26   male       08/14/2025   2024/06/03
 784        1095  Regina Wilson   73   male  December 31, 25   2024/12/14,
 ('Thomas Smith',):      patient_id  patient_name  age  gender  appointment_date booking_date
 273        1054  Thomas Smith   82       1   November 23, 25   2024/12/07
 435        1067  Thomas Smith   54  Female  September 11, 25   2025/09/05}

In [8]:
#age checking

In [9]:
max(df['age'])

90

In [10]:
min(df['age'])

18

In [11]:
#writing patients names in alphabetical order
df = df.sort_values('patient_name')
df

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
398,1074,Aaron Clay,87,M,31-Oct-2025,05/22/2025,Timothy Barker,Cardiology,€312.88,Yes
994,1068,Aaron Holder,19,Male,2026/01/26,"November 28, 24",Lauren Ayers,General,Rs377.38,Y
549,1010,Aaron Young,60,M,26-Jan-2026,05/09/2024,Wendy Cochran,Cardiology,Rs222.33,1
501,1073,Abigail Holt,50,0,09/11/2025,2025/03/14,Jacob Mays,Neurology,$343.79,Yes
833,1027,Abigail Townsend,54,F,2025/12/10,"March 08, 25",Allison Salazar,Orthopedics,$406.61,Y
...,...,...,...,...,...,...,...,...,...,...
346,1003,Zachary Cross,61,1,"July 31, 25",2025/04/23,Toni Rodriguez,Neurology,£317.84,0
271,1098,Zachary Frazier,88,Female,14-Feb-2026,2024/12/27,Tamara Thompson,Orthopedics,$481.92,0
243,1015,Zachary Jones,53,0,10/03/2025,01-Jul-2025,Alexander Lee,Orthopedics,£304.51,0
588,1023,Zachary Lewis,46,Female,"February 07, 26",12/19/2024,Gary Washington,Neurology,$351.94,1
465,1031,Zachary Williams,33,1,"September 13, 25",2024/07/02,Selena Brown,Orthopedics,£458.83,1

In [12]:
#reset index and drop the old index
df = df.reset_index(drop=True)
df

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1074,Aaron Clay,87,M,31-Oct-2025,05/22/2025,Timothy Barker,Cardiology,€312.88,Yes
1,1068,Aaron Holder,19,Male,2026/01/26,"November 28, 24",Lauren Ayers,General,Rs377.38,Y
2,1010,Aaron Young,60,M,26-Jan-2026,05/09/2024,Wendy Cochran,Cardiology,Rs222.33,1
3,1073,Abigail Holt,50,0,09/11/2025,2025/03/14,Jacob Mays,Neurology,$343.79,Yes
4,1027,Abigail Townsend,54,F,2025/12/10,"March 08, 25",Allison Salazar,Orthopedics,$406.61,Y
...,...,...,...,...,...,...,...,...,...,...
995,1003,Zachary Cross,61,1,"July 31, 25",2025/04/23,Toni Rodriguez,Neurology,£317.84,0
996,1098,Zachary Frazier,88,Female,14-Feb-2026,2024/12/27,Tamara Thompson,Orthopedics,$481.92,0
997,1015,Zachary Jones,53,0,10/03/2025,01-Jul-2025,Alexander Lee,Orthopedics,£304.51,0
998,1023,Zachary Lewis,46,Female,"February 07, 26",12/19/2024,Gary Washington,Neurology,$351.94,1
999,1031,Zachary Williams,33,1,"September 13, 25",2024/07/02,Selena Brown,Orthopedics,£458.83,1

In [13]:
#change patients ID

In [14]:
#set new IDs, from 1000 to 1999
df['patient_id'] = range(1000, 1000 + len(df))
df

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1000,Aaron Clay,87,M,31-Oct-2025,05/22/2025,Timothy Barker,Cardiology,€312.88,Yes
1,1001,Aaron Holder,19,Male,2026/01/26,"November 28, 24",Lauren Ayers,General,Rs377.38,Y
2,1002,Aaron Young,60,M,26-Jan-2026,05/09/2024,Wendy Cochran,Cardiology,Rs222.33,1
3,1003,Abigail Holt,50,0,09/11/2025,2025/03/14,Jacob Mays,Neurology,$343.79,Yes
4,1004,Abigail Townsend,54,F,2025/12/10,"March 08, 25",Allison Salazar,Orthopedics,$406.61,Y
...,...,...,...,...,...,...,...,...,...,...
995,1995,Zachary Cross,61,1,"July 31, 25",2025/04/23,Toni Rodriguez,Neurology,£317.84,0
996,1996,Zachary Frazier,88,Female,14-Feb-2026,2024/12/27,Tamara Thompson,Orthopedics,$481.92,0
997,1997,Zachary Jones,53,0,10/03/2025,01-Jul-2025,Alexander Lee,Orthopedics,£304.51,0
998,1998,Zachary Lewis,46,Female,"February 07, 26",12/19/2024,Gary Washington,Neurology,$351.94,1
999,1999,Zachary Williams,33,1,"September 13, 25",2024/07/02,Selena Brown,Orthopedics,£458.83,1

In [15]:
#checkpoint 1. names and IDs 
df_names = df
df_checkpoint = df_names.copy()
df_checkpoint

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1000,Aaron Clay,87,M,31-Oct-2025,05/22/2025,Timothy Barker,Cardiology,€312.88,Yes
1,1001,Aaron Holder,19,Male,2026/01/26,"November 28, 24",Lauren Ayers,General,Rs377.38,Y
2,1002,Aaron Young,60,M,26-Jan-2026,05/09/2024,Wendy Cochran,Cardiology,Rs222.33,1
3,1003,Abigail Holt,50,0,09/11/2025,2025/03/14,Jacob Mays,Neurology,$343.79,Yes
4,1004,Abigail Townsend,54,F,2025/12/10,"March 08, 25",Allison Salazar,Orthopedics,$406.61,Y
...,...,...,...,...,...,...,...,...,...,...
995,1995,Zachary Cross,61,1,"July 31, 25",2025/04/23,Toni Rodriguez,Neurology,£317.84,0
996,1996,Zachary Frazier,88,Female,14-Feb-2026,2024/12/27,Tamara Thompson,Orthopedics,$481.92,0
997,1997,Zachary Jones,53,0,10/03/2025,01-Jul-2025,Alexander Lee,Orthopedics,£304.51,0
998,1998,Zachary Lewis,46,Female,"February 07, 26",12/19/2024,Gary Washington,Neurology,$351.94,1
999,1999,Zachary Williams,33,1,"September 13, 25",2024/07/02,Selena Brown,Orthopedics,£458.83,1

In [16]:
#inconsistent naming of genders

In [17]:
df_names['gender'].unique()

<ArrowStringArray>
['M', 'Male', '0', 'F', 'Female', '1', nan, 'male', 'female']
Length: 9, dtype: str

In [18]:
df_names['gender'] = df_names['gender'].replace({'f': 'F', 'female': 'F', 'Female': 'F', '0': 'F', 'm': 'M', 'male': 'M', 'Male': 'M', '1': 'M'})
df_names['gender'] = df_names['gender'].fillna('X')
df_names['gender'].unique()

<ArrowStringArray>
['M', 'F', 'X']
Length: 3, dtype: str

In [19]:
#inconsistent answers to "follow_up_required"

In [20]:
df_names['follow_up_required'].unique()

<ArrowStringArray>
['Yes', 'Y', '1', 'No', '0', 'N']
Length: 6, dtype: str

In [21]:
df_names['follow_up_required'] = df_names['follow_up_required'].replace({'No': '0', 'N': '0', 'Yes': '1', 'Y': '1'})
df_names['follow_up_required'].unique()

<ArrowStringArray>
['1', '0']
Length: 2, dtype: str

In [22]:
#checkpoint 2. genders and answers
df_gen_an = df_names
df_checkpoint = df_gen_an.copy()
df_checkpoint

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1000,Aaron Clay,87,M,31-Oct-2025,05/22/2025,Timothy Barker,Cardiology,€312.88,1
1,1001,Aaron Holder,19,M,2026/01/26,"November 28, 24",Lauren Ayers,General,Rs377.38,1
2,1002,Aaron Young,60,M,26-Jan-2026,05/09/2024,Wendy Cochran,Cardiology,Rs222.33,1
3,1003,Abigail Holt,50,F,09/11/2025,2025/03/14,Jacob Mays,Neurology,$343.79,1
4,1004,Abigail Townsend,54,F,2025/12/10,"March 08, 25",Allison Salazar,Orthopedics,$406.61,1
...,...,...,...,...,...,...,...,...,...,...
995,1995,Zachary Cross,61,M,"July 31, 25",2025/04/23,Toni Rodriguez,Neurology,£317.84,0
996,1996,Zachary Frazier,88,F,14-Feb-2026,2024/12/27,Tamara Thompson,Orthopedics,$481.92,0
997,1997,Zachary Jones,53,F,10/03/2025,01-Jul-2025,Alexander Lee,Orthopedics,£304.51,0
998,1998,Zachary Lewis,46,F,"February 07, 26",12/19/2024,Gary Washington,Neurology,$351.94,1
999,1999,Zachary Williams,33,M,"September 13, 25",2024/07/02,Selena Brown,Orthopedics,£458.83,1

In [23]:
#inconsistent date types in appointment_date and booking_date

In [24]:
df_gen_an['appointment_date']

0           31-Oct-2025
1            2026/01/26
2           26-Jan-2026
3            09/11/2025
4            2025/12/10
             ...
995         July 31, 25
996         14-Feb-2026
997          10/03/2025
998     February 07, 26
999    September 13, 25
Name: appointment_date, Length: 1000, dtype: str

In [25]:
df_gen_an['appointment_date'] = pd.to_datetime(df_gen_an['appointment_date'], format='mixed')
df_gen_an['appointment_date']

0     2025-10-31
1     2026-01-26
2     2026-01-26
3     2025-09-11
4     2025-12-10
         ...
995   2025-07-31
996   2026-02-14
997   2025-10-03
998   2026-02-07
999   2025-09-13
Name: appointment_date, Length: 1000, dtype: datetime64[us]

In [26]:
df_gen_an['booking_date']

0           05/22/2025
1      November 28, 24
2           05/09/2024
3           2025/03/14
4         March 08, 25
            ...
995         2025/04/23
996         2024/12/27
997        01-Jul-2025
998         12/19/2024
999         2024/07/02
Name: booking_date, Length: 1000, dtype: str

In [27]:
df_gen_an['booking_date'] = pd.to_datetime(df_gen_an['booking_date'], format='mixed')
df_gen_an['booking_date']

0     2025-05-22
1     2024-11-28
2     2024-05-09
3     2025-03-14
4     2025-03-08
         ...
995   2025-04-23
996   2024-12-27
997   2025-07-01
998   2024-12-19
999   2024-07-02
Name: booking_date, Length: 1000, dtype: datetime64[us]

In [28]:
#checking the dates logic
invalid_dates = df_gen_an[df_gen_an['appointment_date'] < df_gen_an['booking_date']]
invalid_dates

Empty DataFrame
Columns: [patient_id, patient_name, age, gender, appointment_date, booking_date, doctor, department, billing_amount, follow_up_required]
Index: []

In [29]:
#checkpoint 3. dates
df_dates = df_gen_an
df_checkpoint = df_dates.copy()
df_checkpoint

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1000,Aaron Clay,87,M,2025-10-31,2025-05-22,Timothy Barker,Cardiology,€312.88,1
1,1001,Aaron Holder,19,M,2026-01-26,2024-11-28,Lauren Ayers,General,Rs377.38,1
2,1002,Aaron Young,60,M,2026-01-26,2024-05-09,Wendy Cochran,Cardiology,Rs222.33,1
3,1003,Abigail Holt,50,F,2025-09-11,2025-03-14,Jacob Mays,Neurology,$343.79,1
4,1004,Abigail Townsend,54,F,2025-12-10,2025-03-08,Allison Salazar,Orthopedics,$406.61,1
...,...,...,...,...,...,...,...,...,...,...
995,1995,Zachary Cross,61,M,2025-07-31,2025-04-23,Toni Rodriguez,Neurology,£317.84,0
996,1996,Zachary Frazier,88,F,2026-02-14,2024-12-27,Tamara Thompson,Orthopedics,$481.92,0
997,1997,Zachary Jones,53,F,2025-10-03,2025-07-01,Alexander Lee,Orthopedics,£304.51,0
998,1998,Zachary Lewis,46,F,2026-02-07,2024-12-19,Gary Washington,Neurology,$351.94,1
999,1999,Zachary Williams,33,M,2025-09-13,2024-07-02,Selena Brown,Orthopedics,£458.83,1

In [30]:
#convert different currencies to $

In [31]:
#checking for nan values
pd.isna(df_dates['billing_amount']).sum()

np.int64(50)

In [32]:
#convert different currencies to $ depending on currency, ignoring the nan values
pd.options.display.float_format = '{:.2f}'.format
money = df_dates['billing_amount'].astype(str)

conversion_map = { #14.05.2026 
    "€": "1.17*", 
    "Rs": "0.01*", 
    "\$": "1*", 
    "£": "1.35*"
}

df_dates['billing_usd'] = money.replace(conversion_map, regex=True).map(pd.eval, na_action='ignore')
df_dates['billing_usd']

0     366.07
1       3.77
2       2.22
3     343.79
4     406.61
       ...
995   429.08
996   481.92
997   411.09
998   351.94
999   619.42
Name: billing_usd, Length: 1000, dtype: float64

In [33]:
#saving original billing_amount
billing_amount = df_dates['billing_amount']

In [34]:
#dropping original billing_amount
df_dates = df_dates.drop(columns=['billing_amount'])
df_dates

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,follow_up_required,billing_usd
0,1000,Aaron Clay,87,M,2025-10-31,2025-05-22,Timothy Barker,Cardiology,1,366.07
1,1001,Aaron Holder,19,M,2026-01-26,2024-11-28,Lauren Ayers,General,1,3.77
2,1002,Aaron Young,60,M,2026-01-26,2024-05-09,Wendy Cochran,Cardiology,1,2.22
3,1003,Abigail Holt,50,F,2025-09-11,2025-03-14,Jacob Mays,Neurology,1,343.79
4,1004,Abigail Townsend,54,F,2025-12-10,2025-03-08,Allison Salazar,Orthopedics,1,406.61
...,...,...,...,...,...,...,...,...,...,...
995,1995,Zachary Cross,61,M,2025-07-31,2025-04-23,Toni Rodriguez,Neurology,0,429.08
996,1996,Zachary Frazier,88,F,2026-02-14,2024-12-27,Tamara Thompson,Orthopedics,0,481.92
997,1997,Zachary Jones,53,F,2025-10-03,2025-07-01,Alexander Lee,Orthopedics,0,411.09
998,1998,Zachary Lewis,46,F,2026-02-07,2024-12-19,Gary Washington,Neurology,1,351.94
999,1999,Zachary Williams,33,M,2025-09-13,2024-07-02,Selena Brown,Orthopedics,1,619.42

In [35]:
#filling nan values with average value of each department
df_dates["billing_usd"] = df_dates.groupby("department")["billing_usd"].transform(lambda x: x.fillna(x.mean()))
df_dates["billing_usd"]

0     366.07
1       3.77
2       2.22
3     343.79
4     406.61
       ...
995   429.08
996   481.92
997   411.09
998   351.94
999   619.42
Name: billing_usd, Length: 1000, dtype: float64

In [36]:
#checkpoint 4. money
df_money = df_dates
df_checkpoint = df_money.copy()
df_checkpoint

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,follow_up_required,billing_usd
0,1000,Aaron Clay,87,M,2025-10-31,2025-05-22,Timothy Barker,Cardiology,1,366.07
1,1001,Aaron Holder,19,M,2026-01-26,2024-11-28,Lauren Ayers,General,1,3.77
2,1002,Aaron Young,60,M,2026-01-26,2024-05-09,Wendy Cochran,Cardiology,1,2.22
3,1003,Abigail Holt,50,F,2025-09-11,2025-03-14,Jacob Mays,Neurology,1,343.79
4,1004,Abigail Townsend,54,F,2025-12-10,2025-03-08,Allison Salazar,Orthopedics,1,406.61
...,...,...,...,...,...,...,...,...,...,...
995,1995,Zachary Cross,61,M,2025-07-31,2025-04-23,Toni Rodriguez,Neurology,0,429.08
996,1996,Zachary Frazier,88,F,2026-02-14,2024-12-27,Tamara Thompson,Orthopedics,0,481.92
997,1997,Zachary Jones,53,F,2025-10-03,2025-07-01,Alexander Lee,Orthopedics,0,411.09
998,1998,Zachary Lewis,46,F,2026-02-07,2024-12-19,Gary Washington,Neurology,1,351.94
999,1999,Zachary Williams,33,M,2025-09-13,2024-07-02,Selena Brown,Orthopedics,1,619.42

In [37]:
#creating new column for calculating days of waiting between booking and appointment
df_money["waiting_days"] = (
    df_money["appointment_date"] - df_money["booking_date"]
).dt.days
df_money

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,follow_up_required,billing_usd,waiting_days
0,1000,Aaron Clay,87,M,2025-10-31,2025-05-22,Timothy Barker,Cardiology,1,366.07,162
1,1001,Aaron Holder,19,M,2026-01-26,2024-11-28,Lauren Ayers,General,1,3.77,424
2,1002,Aaron Young,60,M,2026-01-26,2024-05-09,Wendy Cochran,Cardiology,1,2.22,627
3,1003,Abigail Holt,50,F,2025-09-11,2025-03-14,Jacob Mays,Neurology,1,343.79,181
4,1004,Abigail Townsend,54,F,2025-12-10,2025-03-08,Allison Salazar,Orthopedics,1,406.61,277
...,...,...,...,...,...,...,...,...,...,...,...
995,1995,Zachary Cross,61,M,2025-07-31,2025-04-23,Toni Rodriguez,Neurology,0,429.08,99
996,1996,Zachary Frazier,88,F,2026-02-14,2024-12-27,Tamara Thompson,Orthopedics,0,481.92,414
997,1997,Zachary Jones,53,F,2025-10-03,2025-07-01,Alexander Lee,Orthopedics,0,411.09,94
998,1998,Zachary Lewis,46,F,2026-02-07,2024-12-19,Gary Washington,Neurology,1,351.94,415
999,1999,Zachary Williams,33,M,2025-09-13,2024-07-02,Selena Brown,Orthopedics,1,619.42,438

In [38]:
#creating new column for age groups
df_money['age_group'] = pd.cut(df_money['age'], bins = [18,35,50,70,90], labels = ['Young adult', 'Adult', 'Middle age', 'Senior'])
df_money['age_group']

0           Senior
1      Young adult
2       Middle age
3            Adult
4       Middle age
          ...
995     Middle age
996         Senior
997     Middle age
998          Adult
999    Young adult
Name: age_group, Length: 1000, dtype: category
Categories (4, str): ['Young adult' < 'Adult' < 'Middle age' < 'Senior']

In [39]:
#reordering columns

In [40]:
df_money.columns.values

<ArrowStringArray>
[        'patient_id',       'patient_name',                'age',
             'gender',   'appointment_date',       'booking_date',
             'doctor',         'department', 'follow_up_required',
        'billing_usd',       'waiting_days',          'age_group']
Length: 12, dtype: str

In [41]:
column_names_reordered = ['patient_id','patient_name','age','age_group', 'gender','appointment_date','booking_date', 'waiting_days', 'doctor','department', 'billing_usd', 'follow_up_required',]

In [42]:
df_money = df_money[column_names_reordered]
df_money

,patient_id,patient_name,age,age_group,gender,appointment_date,booking_date,waiting_days,doctor,department,billing_usd,follow_up_required
0,1000,Aaron Clay,87,Senior,M,2025-10-31,2025-05-22,162,Timothy Barker,Cardiology,366.07,1
1,1001,Aaron Holder,19,Young adult,M,2026-01-26,2024-11-28,424,Lauren Ayers,General,3.77,1
2,1002,Aaron Young,60,Middle age,M,2026-01-26,2024-05-09,627,Wendy Cochran,Cardiology,2.22,1
3,1003,Abigail Holt,50,Adult,F,2025-09-11,2025-03-14,181,Jacob Mays,Neurology,343.79,1
4,1004,Abigail Townsend,54,Middle age,F,2025-12-10,2025-03-08,277,Allison Salazar,Orthopedics,406.61,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1995,Zachary Cross,61,Middle age,M,2025-07-31,2025-04-23,99,Toni Rodriguez,Neurology,429.08,0
996,1996,Zachary Frazier,88,Senior,F,2026-02-14,2024-12-27,414,Tamara Thompson,Orthopedics,481.92,0
997,1997,Zachary Jones,53,Middle age,F,2025-10-03,2025-07-01,94,Alexander Lee,Orthopedics,411.09,0
998,1998,Zachary Lewis,46,Adult,F,2026-02-07,2024-12-19,415,Gary Washington,Neurology,351.94,1
999,1999,Zachary Williams,33,Young adult,M,2025-09-13,2024-07-02,438,Selena Brown,Orthopedics,619.42,1

In [43]:
#checkpoint 5. clean dataset
df_clean = df_money
df_checkpoint = df_clean.copy()
df_checkpoint

,patient_id,patient_name,age,age_group,gender,appointment_date,booking_date,waiting_days,doctor,department,billing_usd,follow_up_required
0,1000,Aaron Clay,87,Senior,M,2025-10-31,2025-05-22,162,Timothy Barker,Cardiology,366.07,1
1,1001,Aaron Holder,19,Young adult,M,2026-01-26,2024-11-28,424,Lauren Ayers,General,3.77,1
2,1002,Aaron Young,60,Middle age,M,2026-01-26,2024-05-09,627,Wendy Cochran,Cardiology,2.22,1
3,1003,Abigail Holt,50,Adult,F,2025-09-11,2025-03-14,181,Jacob Mays,Neurology,343.79,1
4,1004,Abigail Townsend,54,Middle age,F,2025-12-10,2025-03-08,277,Allison Salazar,Orthopedics,406.61,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1995,Zachary Cross,61,Middle age,M,2025-07-31,2025-04-23,99,Toni Rodriguez,Neurology,429.08,0
996,1996,Zachary Frazier,88,Senior,F,2026-02-14,2024-12-27,414,Tamara Thompson,Orthopedics,481.92,0
997,1997,Zachary Jones,53,Middle age,F,2025-10-03,2025-07-01,94,Alexander Lee,Orthopedics,411.09,0
998,1998,Zachary Lewis,46,Adult,F,2026-02-07,2024-12-19,415,Gary Washington,Neurology,351.94,1
999,1999,Zachary Williams,33,Young adult,M,2025-09-13,2024-07-02,438,Selena Brown,Orthopedics,619.42,1

In [44]:
df_clean.to_csv('clinic-appointments-clean.csv')